name: Lint Code with Flake8

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest  # Fixed typo: 'rubns-on' ➜ 'runs-on'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: |
          flake8 .
